require('./canonical-contract.test.js')
require('./operation-ledger.test.js')
require('./ledger-store-model.test.js')
require('./fake-cli-model.test.js')
require('./service-lifecycle.test.js')
require('./scaffold-contract.test.js')
require('./time-tracking-model.test.js')
